// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpvggsvvrmwmukdcxjqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdmdnc3Z2cm13bXVrZGN4anFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNDU4MjIsImV4cCI6MjA1MDYyMTgyMn0.gE2RZQo0NAVhZNTikskQrkS6ZtXCnJUhPsLaXA74-14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);